word_list = [
    "ATTACK ON TITAN",
    "TORADORA",
    "KONOSUBA",
    "DEMON SLAYER",
    "YOUR LIE IN APRIL",
    "CLANNAD",
    "YOUR NAME",
    "I WANT TO EAT YOUR PANCREAS",
    "REDO OF HEALER",
    "HAIKYUU",
    "HUNTER X HUNTER",
    "ONE PIECE",
    "NARUTO",
    "DEATH NOTE"
    "THE GARDEN OF WORDS"
    "A SILENT VOICE",
    "DARLING IN THE FRANXX",
    "KUROKO NO BASKET",
    "QUINTESSENTIAL QUINTUPLETS",
    "FIRE FORCE"
]
